require 'rubygems'
require 'bundler/setup'
require 'RMagick'
require 'pixelmapper/color.rb'
require 'magick/pixel.rb'
require 'pixelmapper/perler.rb'
require 'pixelmapper/grid.rb'
require 'pixelmapper/palette.rb'